### ISSUE TITLE
Break/Place reverse-progression when false fails to increment

### ISSUE THREAD

**Issue by FesterHead** [FesterHead/Quests#7]
**Description of Error**
When `reverse-progression: false` is configured for `break` or `place` tasks they fail to increment as expected when a block is broken or placed.

**To Reproduce**
* Set `reverse-progression: false` for a break task
* break the block
* progress is not incremented

Sample tasks:
```
  task01:
    type: "break"
    amount: 10
    item: "mossy_cobblestone"
    present: "break"
    past: "broken"
    reverse-progression: false
  task02:
    type: "place"
    amount: 10
    item: "mossy_cobblestone"
    present: "place"
    past: "placed"
```

**Server details:**
 - Minecraft Version: all
 - Mod Name: all
 - Plugins: n/a

**Quests Plugin version:**
 - Version: 3.4.2 and below
